import Ring1 from "./ring-1.png"
import Ring2 from "./ring-2.png"
import Ring3 from "./ring-3.png"
import Ring4 from "./ring-4.png"
import Ring5 from "./ring-5.png"
import Ring6 from "./ring-6.png"
import Ring7 from "./ring-7.png"
import Ring8 from "./ring-8.png"
import Ring9 from "./ring-9.png"
import Ring10 from "./ring-10.png"
import Hat1 from "./hat-1.png"
import Hat2 from "./hat-2.png"
import Hat3 from "./hat-3.png"

export { Ring1, Ring2, Ring3, Ring4, Ring5, Ring6, Ring7, Ring8, Ring9, Ring10, Hat1, Hat2, Hat3 }
